# Generated by Django 2.2.5 on 2019-10-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('thumbnail', models.ImageField(editable=False, upload_to='')),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
