# Generated by Django 2.0.13 on 2019-12-31 01:53

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('attendees', models.PositiveIntegerField()),
                ('pork', models.PositiveIntegerField()),
                ('chicken', models.PositiveIntegerField()),
                ('vegetarian', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to=pages.models.image_upload_handler),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='thumbnail',
            field=models.ImageField(upload_to=pages.models.thumbnail_image_upload_handler),
        ),
    ]
